baseURL: http://example.com/
theme: hugo-theme-introduction
DefaultContentLanguage: en
params:
  dateFormat: Jan 2, 2006
#  email: youremail@email.com
  fadeIn: yes
  fadeInIndex: no
  favicon: /img/fav.ico
  giscus:
    category: Comments
    category-id: enter-category-id
    emit-metadata: '0'
    lang: en
    mapping: pathname
    reactions-enabled: '1'
    repo-id: enter-repo-id
    theme: light
  home:
    allPostsArchiveFormat: yes
    introHeight: fullheight
    localTime: yes
#    numberOfProjectsToShow: 3
#    showAllPosts: no
#    showLatest: yes
    showLatest: no
    timeFormat: en-US
    timeZone: America/Los_Angeles
  # projects:
  #   useTwoColumns: no
  share:
    facebook: yes
    pinterest: yes
    twitter: yes
  showMenu: yes
  showRSSButton: no
  # social:
  #   - icon: twitter
  #     icon_pack: fab
  #     url: https://twitter.com/
  #   - icon: facebook-f
  #     icon_pack: fab
  #     url: https://facebook.com/
  #   - icon: linkedin-in
  #     icon_pack: fab
  #     url: https://linkedin.com/
  #   - icon: paper-plane
  #     icon_pack: fas
  #     url: mailto:youremail@email.com
  #   - html_attributes: rel="me"
  #     icon: mastodon
  #     icon_pack: fab
  #     url: https://mastodon.social/
  themeStyle: auto
taxonomies:
  series: series
  tag: tags
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: no
    lineNumbersInTable: yes
    style: solarized-dark
    tabWidth: 4
languages:
  # de:
  #   contentDir: content/de
  #   languageCode: de
  #   languageName: Deutsch
  #   params:
  #     dateFormat: 2. January 2006
  #     description: Beschreibung der Webseite
  #   title: Vorstellung
  #   weight: 2
  en:
    contentDir: content/en
    languageCode: en-us
    languageName: English
    params:
      description: Website Description
    title: PsychDevSolutions
    weight: 0
  # es:
  #   contentDir: content/es
  #   languageCode: es
  #   languageName: Español
  #   params:
  #     description: Descripcion del sitio web
  #   title: Introducción
  #   weight: 1
